import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import ts from 'typescript';
const data = new Map();
globalThis.localStorage = {getItem:key => data.get(key) ?? null, setItem:(key,value) => data.set(key,value), removeItem:key => data.delete(key)};
const source = await readFile(new URL('../apps/manual-studio/src/aiCredentials.ts',import.meta.url),'utf8');
const js = ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText;
const {readAiCredential,saveAiCredential,hasUnassignedAiCredential,assignLegacyAiCredential} = await import(`data:text/javascript;base64,${Buffer.from(js).toString('base64')}`);
data.set('manual-studio-ai-api-key','unowned-old-key');
assert.equal(readAiCredential('/project-a','https://api.example/v1'),'');
assert.equal(data.has('manual-studio-ai-api-key'),false);
assert.equal(hasUnassignedAiCredential(),true);
assert.equal(assignLegacyAiCredential('/chosen-project','https://chosen.example/v1'),'unowned-old-key');
assert.equal(readAiCredential('/chosen-project','https://chosen.example/v1'),'unowned-old-key');
assert.equal(hasUnassignedAiCredential(),false);
saveAiCredential('/project-a','https://api.example/v1','key-a');
assert.equal(readAiCredential('/project-a/','https://API.example/v1/'),'key-a');
assert.equal(readAiCredential('/project-b','https://api.example/v1'),'');
assert.equal(readAiCredential('/project-a','https://other.example/v1'),'');
saveAiCredential('/project-a','https://other.example/v1','key-b');
saveAiCredential('/project-a','https://api.example/v1','');
assert.equal(readAiCredential('/project-a','https://other.example/v1'),'key-b');
console.log('AI credentials checks passed: project/endpoint isolation, normalization, legacy-key reset.');
