use crate::model::{DuplicateBlock, ModuleInfo};
use rustpython_ast::{self as ast, Visitor};
use rustpython_parser::{source_code::LineIndex, Parse};
use std::collections::HashMap;
use std::fs;
use std::path::Path;

struct ImportLines<'a> {
    index: &'a LineIndex,
    lines: Vec<bool>,
}

impl ImportLines<'_> {
    fn mark(&mut self, start: ast::text_size::TextSize, end: ast::text_size::TextSize) {
        let first = self.index.line_index(start).get() as usize - 1;
        let last = self
            .index
            .line_index(end - ast::text_size::TextSize::new(1))
            .get() as usize
            - 1;
        for line in first..=last {
            self.lines[line] = true;
        }
    }
}

impl Visitor for ImportLines<'_> {
    fn visit_stmt_import(&mut self, node: ast::StmtImport) {
        self.mark(node.range.start(), node.range.end());
    }

    fn visit_stmt_import_from(&mut self, node: ast::StmtImportFrom) {
        self.mark(node.range.start(), node.range.end());
    }
}

pub(crate) fn actionable_lines(source: &str) -> Vec<bool> {
    let lines: Vec<_> = source.lines().collect();
    let mut visitor = ImportLines {
        index: &LineIndex::from_source_text(source),
        lines: vec![false; lines.len()],
    };
    if let Ok(suite) = ast::Suite::parse(source, "<duplicate-filter>") {
        for stmt in suite {
            visitor.visit_stmt(stmt);
        }
    }
    lines
        .iter()
        .enumerate()
        .map(|(index, line)| {
            let line = line.trim();
            !line.is_empty()
                && !line.starts_with('#')
                && !visitor.lines[index]
                && !is_boilerplate_line(line)
        })
        .collect()
}

fn is_boilerplate_line(line: &str) -> bool {
    matches!(
        line,
        "pass"
            | "..."
            | "return None"
            | "raise NotImplementedError"
            | "raise NotImplementedError()"
    ) || line.starts_with("def ")
        || line.starts_with("async def ")
        || line.starts_with("class ")
        || line.starts_with('@')
        || line.starts_with("\"\"\"")
        || line.starts_with("'''")
}

pub(crate) fn is_generated_file(path: &Path, source: &str) -> bool {
    if path.components().any(|component| {
        matches!(
            component.as_os_str().to_str(),
            Some("generated" | "__generated__" | "vendor" | "third_party" | "migrations")
        )
    }) {
        return true;
    }
    source.lines().take(20).any(|line| {
        let line = line.trim().to_ascii_lowercase();
        line.starts_with('#')
            && [
                "@generated",
                "auto-generated",
                "automatically generated",
                "generated by",
                "do not edit",
            ]
            .iter()
            .any(|marker| line.contains(marker))
    })
}

pub(crate) fn actionable_line_count(lines: &[bool], start: usize, count: usize) -> usize {
    lines
        .get(start.saturating_sub(1)..start.saturating_sub(1).saturating_add(count))
        .map_or(0, |span| span.iter().filter(|&&line| line).count())
}

#[derive(Clone)]
struct FunctionRange {
    first: usize,
    last: usize,
    name: String,
    signature: String,
}

struct FunctionRanges<'a> {
    index: &'a LineIndex,
    functions: &'a [crate::model::FunctionInfo],
    ranges: Vec<FunctionRange>,
}

impl FunctionRanges<'_> {
    fn add(
        &mut self,
        name: String,
        start: ast::text_size::TextSize,
        end: ast::text_size::TextSize,
    ) {
        let first = self.index.line_index(start).get() as usize;
        let last = self
            .index
            .line_index(end - ast::text_size::TextSize::new(1))
            .get() as usize;
        let signature = self
            .functions
            .iter()
            .find(|function| function.line == first && function.name == name)
            .map(|function| function.signature.clone())
            .unwrap_or_default();
        self.ranges.push(FunctionRange {
            first,
            last,
            name,
            signature,
        });
    }
}

impl Visitor for FunctionRanges<'_> {
    fn visit_stmt_function_def(&mut self, node: ast::StmtFunctionDef) {
        self.add(node.name.to_string(), node.range.start(), node.range.end());
        self.generic_visit_stmt_function_def(node);
    }

    fn visit_stmt_async_function_def(&mut self, node: ast::StmtAsyncFunctionDef) {
        self.add(node.name.to_string(), node.range.start(), node.range.end());
        self.generic_visit_stmt_async_function_def(node);
    }
}

pub(crate) fn enrich_duplicate_blocks(blocks: &mut [DuplicateBlock], modules: &[ModuleInfo]) {
    let mut contexts = HashMap::new();
    for module in modules {
        if !blocks
            .iter()
            .any(|block| block.first_module == module.id || block.second_module == module.id)
        {
            continue;
        }
        let Ok(source) = fs::read_to_string(&module.absolute_path) else {
            continue;
        };
        let Ok(suite) = ast::Suite::parse(&source, "<duplicate-context>") else {
            continue;
        };
        let index = LineIndex::from_source_text(&source);
        let mut visitor = FunctionRanges {
            index: &index,
            functions: &module.functions,
            ranges: Vec::new(),
        };
        for stmt in suite {
            visitor.visit_stmt(stmt);
        }
        contexts.insert(module.id.as_str(), visitor.ranges);
    }
    for block in blocks {
        for (module, line, function, signature) in [
            (
                &block.first_module,
                block.first_line,
                &mut block.first_function,
                &mut block.first_signature,
            ),
            (
                &block.second_module,
                block.second_line,
                &mut block.second_function,
                &mut block.second_signature,
            ),
        ] {
            if let Some(found) = contexts.get(module.as_str()).and_then(|ranges| {
                ranges
                    .iter()
                    .filter(|range| range.first <= line && line <= range.last)
                    .min_by_key(|range| range.last - range.first)
            }) {
                *function = Some(found.name.clone());
                if !found.signature.is_empty() {
                    *signature = Some(found.signature.clone());
                }
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn excludes_imports_and_template_lines() {
        let source = "from pathlib import (\n    Path,\n)\ndef run():\n    pass\n    ...\n    return None\n    value = 1\n";
        assert_eq!(
            actionable_lines(source),
            vec![false, false, false, false, false, false, false, true]
        );
    }

    #[test]
    fn recognizes_generated_headers_and_directories() {
        assert!(is_generated_file(
            Path::new("src/normal.py"),
            "# Generated by a tool. Do not edit.\nvalue = 1\n"
        ));
        assert!(is_generated_file(
            Path::new("src/generated/model.py"),
            "value = 1\n"
        ));
        assert!(!is_generated_file(Path::new("src/model.py"), "value = 1\n"));
    }
}
