//! Generate a self-contained MkDocs project from an analysis snapshot.

use crate::model::{AnalysisResult, ModuleInfo};
use serde::Deserialize;
use std::collections::{BTreeMap, BTreeSet, HashMap};
use std::fs;
use std::path::{Path, PathBuf};
use std::sync::OnceLock;

const MARKER: &str = ".moduleloom-generated";
const GENERATED_HEADER: &str = "<!-- Generated by ModuleLoom. Edits will be replaced. -->\n\n";

pub fn generate(result: &AnalysisResult, output: &Path) -> Result<(), String> {
    generate_with_lang(result, output, "auto")
}

pub fn generate_with_lang(
    result: &AnalysisResult,
    output: &Path,
    lang: &str,
) -> Result<(), String> {
    let lang = resolve_lang(lang)?;
    let labels = labels_for_lang(&lang);
    if output.exists() {
        if !output.is_dir() {
            return Err(format!("Output is not a directory: {}", output.display()));
        }
        let unmarked = fs::read_dir(output)
            .map_err(|error| error.to_string())?
            .next()
            .is_some()
            && !output.join(MARKER).exists();
        if unmarked {
            return Err(format!(
                "Output directory is not empty and was not generated by ModuleLoom: {}",
                output.display()
            ));
        }
    }
    fs::create_dir_all(output.join("docs/modules")).map_err(|error| error.to_string())?;
    fs::create_dir_all(output.join("docs/javascripts")).map_err(|error| error.to_string())?;

    let mut modules: Vec<&ModuleInfo> = result.modules.iter().collect();
    modules.sort_by(|a, b| a.id.cmp(&b.id).then(a.relative_path.cmp(&b.relative_path)));
    let pages: BTreeMap<&str, String> = modules
        .iter()
        .enumerate()
        .map(|(index, module)| (module.id.as_str(), format!("modules/{index:04}.md")))
        .collect();

    let old_pages = fs::read_to_string(output.join(MARKER)).unwrap_or_default();
    for old_page in old_pages.lines() {
        if !old_page.starts_with("modules/")
            || old_page.contains("..")
            || !old_page.ends_with(".md")
        {
            continue;
        }
        if !pages.values().any(|page| page == old_page) {
            let path = output.join("docs").join(old_page);
            if fs::read_to_string(&path).is_ok_and(|content| content.starts_with(GENERATED_HEADER))
            {
                fs::remove_file(path).map_err(|error| error.to_string())?;
            }
        }
    }

    let project_name = result
        .root_path
        .file_name()
        .and_then(|name| name.to_str())
        .unwrap_or("Python project");
    let mut config = format!(
        "site_name: {}\ntheme:\n  name: material\n  language: {}\nuse_directory_urls: false\nmarkdown_extensions:\n  - pymdownx.superfences:\n      custom_fences:\n        - name: mermaid\n          class: mermaid\n          format: !!python/name:pymdownx.superfences.fence_code_format\nextra_javascript:\n  - javascripts/mermaid.mjs\nnav:\n  - {}: index.md\n",
        serde_json::to_string(project_name).map_err(|error| error.to_string())?,
        lang,
        labels.overview
    );
    config.push_str(&format!("\n# Documentation language: {lang}\n"));
    if !modules.is_empty() {
        config.push_str(&format!("  - {}:\n", labels.modules));
    }
    for module in &modules {
        config.push_str(&format!(
            "      - {}: {}\n",
            serde_json::to_string(&module.id).map_err(|error| error.to_string())?,
            pages[module.id.as_str()]
        ));
    }
    config.push_str(&format!("  - {}: api.md\n", labels.api_catalog));
    write(output.join("mkdocs.yml"), &config)?;
    write_bytes(
        output.join("docs/javascripts/mermaid.min.js"),
        include_bytes!("../assets/mermaid.min.js"),
    )?;
    write_bytes(
        output.join("docs/javascripts/mermaid.LICENSE"),
        include_bytes!("../assets/mermaid.LICENSE"),
    )?;
    write(
        output.join("docs/javascripts/mermaid.mjs"),
        "import './mermaid.min.js';\nwindow.mermaid = globalThis.mermaid;\nwindow.mermaid.initialize({ startOnLoad: true, securityLevel: 'loose' });\n",
    )?;

    let all_ids: BTreeSet<&str> = modules.iter().map(|module| module.id.as_str()).collect();
    let mut index = format!(
        "{GENERATED_HEADER}# {project_name}\n\n## {}\n\n",
        labels.graph
    );
    index.push_str(&diagram(result, &all_ids, &pages, false, labels));
    index.push_str(&format!("\n## {}\n\n", labels.modules));
    for module in &modules {
        index.push_str(&format!(
            "- [{}]({}) — {}\n",
            module.id,
            pages[module.id.as_str()],
            summary(module.docstring.as_deref(), labels)
        ));
    }
    if modules.is_empty() {
        index.push_str(&format!("{}\n", labels.no_modules));
    }
    write(output.join("docs/index.md"), &index)?;

    let mut api = format!("{GENERATED_HEADER}# {}\n\n", labels.api_catalog);
    for module in &modules {
        let page = &pages[module.id.as_str()];
        api.push_str(&format!("## {} [{}]({page})\n\n", labels.module, module.id));
        let module_summary = summary(module.docstring.as_deref(), labels);
        api.push_str(&format!("{}\n\n", module_summary));
        for class in &module.classes {
            api.push_str(&format!(
                "- **{}** [`{}{}`]({page}#api-class-{}) — {}\n",
                labels.class,
                class.name,
                class.signature,
                class.line,
                summary(class.docstring.as_deref(), labels)
            ));
        }
        for function in &module.functions {
            let parent = function
                .parent_class_line
                .and_then(|line| module.classes.iter().find(|class| class.line == line));
            let name = parent.map_or_else(
                || function.name.clone(),
                |class| format!("{}.{}", class.name, function.name),
            );
            api.push_str(&format!(
                "- **{}** [`{}{}`]({page}#api-function-{}) — {}\n",
                labels.callable,
                name,
                function.signature,
                function.line,
                summary(function.docstring.as_deref(), labels)
            ));
        }
        api.push('\n');
    }
    if modules.is_empty() {
        api.push_str(&format!("{}\n", labels.no_modules));
    }
    write(output.join("docs/api.md"), &api)?;

    for module in &modules {
        let connected: BTreeSet<&str> = result
            .edges
            .iter()
            .filter(|edge| edge.source == module.id || edge.target == module.id)
            .flat_map(|edge| [edge.source.as_str(), edge.target.as_str()])
            .chain(std::iter::once(module.id.as_str()))
            .filter(|id| pages.contains_key(id))
            .collect();
        let mut page = format!("{GENERATED_HEADER}# {}\n\n", module.id);
        page.push_str(&diagram(result, &connected, &pages, true, labels));
        page.push_str(&format!("\n[← {}](../index.md)\n\n", labels.back_overview));
        page.push_str(&format!("## {}\n\n", labels.description));
        page.push_str(
            &module
                .docstring
                .as_deref()
                .filter(|text| !text.trim().is_empty())
                .map(format_docstring)
                .unwrap_or_else(|| labels.missing_module_description.clone()),
        );
        page.push_str("\n\n");

        let mut documented = Vec::new();
        for class in &module.classes {
            {
                let docstring = class
                    .docstring
                    .as_deref()
                    .filter(|text| !text.trim().is_empty());
                documented.push((
                    class.line,
                    format!(
                        "<a id=\"api-class-{}\"></a>\n### class `{}`\n\n{}\n\n",
                        class.line,
                        format!("{}{}", class.name, class.signature),
                        docstring
                            .map(format_docstring)
                            .unwrap_or_else(|| labels.missing_description.clone())
                    ),
                ));
            }
        }
        for function in &module.functions {
            {
                let docstring = function
                    .docstring
                    .as_deref()
                    .filter(|text| !text.trim().is_empty());
                let parent = function
                    .parent_class_line
                    .and_then(|line| module.classes.iter().find(|class| class.line == line));
                let name = parent.map_or_else(
                    || function.name.clone(),
                    |class| format!("{}.{}", class.name, function.name),
                );
                documented.push((
                    function.line,
                    format!(
                        "<a id=\"api-function-{}\"></a>\n### {}\n\n`{}{}`\n\n{}\n\n",
                        function.line,
                        name,
                        name,
                        function.signature,
                        docstring
                            .map(format_docstring)
                            .unwrap_or_else(|| labels.missing_description.clone())
                    ),
                ));
            }
        }
        documented.sort_by_key(|(line, _)| *line);
        for (_, section) in documented {
            page.push_str(&section);
        }
        write(output.join("docs").join(&pages[module.id.as_str()]), &page)?;
    }
    let manifest = pages.values().cloned().collect::<Vec<_>>().join("\n");
    write(output.join(MARKER), &manifest)?;
    Ok(())
}

pub fn generate_api_reference(
    result: &AnalysisResult,
    docs_dir: &Path,
    lang: &str,
) -> Result<usize, String> {
    let lang = resolve_lang(lang)?;
    let labels = labels_for_lang(&lang);

    fs::create_dir_all(docs_dir.join("modules")).map_err(|error| error.to_string())?;
    fs::create_dir_all(docs_dir.join("javascripts")).map_err(|error| error.to_string())?;

    let mut modules: Vec<&ModuleInfo> = result.modules.iter().collect();
    modules.sort_by(|a, b| a.id.cmp(&b.id).then(a.relative_path.cmp(&b.relative_path)));
    let pages: BTreeMap<&str, String> = modules
        .iter()
        .enumerate()
        .map(|(index, module)| (module.id.as_str(), format!("modules/{index:04}.md")))
        .collect();

    let marker_path = docs_dir.join("modules").join(MARKER);
    let old_pages = fs::read_to_string(&marker_path).unwrap_or_default();
    for old_page in old_pages.lines() {
        if !old_page.starts_with("modules/")
            || old_page.contains("..")
            || !old_page.ends_with(".md")
        {
            continue;
        }
        if !pages.values().any(|page| page == old_page) {
            let path = docs_dir.join(old_page);
            if fs::read_to_string(&path).is_ok_and(|content| content.starts_with(GENERATED_HEADER))
            {
                let _ = fs::remove_file(path);
            }
        }
    }

    let _ = write_bytes(
        docs_dir.join("javascripts/mermaid.min.js"),
        include_bytes!("../assets/mermaid.min.js"),
    );
    let _ = write_bytes(
        docs_dir.join("javascripts/mermaid.LICENSE"),
        include_bytes!("../assets/mermaid.LICENSE"),
    );
    let _ = write(
        docs_dir.join("javascripts/mermaid.mjs"),
        "import './mermaid.min.js';\nwindow.mermaid = globalThis.mermaid;\nwindow.mermaid.initialize({ startOnLoad: true, securityLevel: 'loose' });\n",
    );

    let mut api = format!("{GENERATED_HEADER}# {}\n\n", labels.api_catalog);
    for module in &modules {
        let page = &pages[module.id.as_str()];
        api.push_str(&format!("## {} [{}]({page})\n\n", labels.module, module.id));
        let module_summary = summary(module.docstring.as_deref(), labels);
        api.push_str(&format!("{}\n\n", module_summary));
        for class in &module.classes {
            api.push_str(&format!(
                "- **{}** [`{}{}`]({page}#api-class-{}) — {}\n",
                labels.class,
                class.name,
                class.signature,
                class.line,
                summary(class.docstring.as_deref(), labels)
            ));
        }
        for function in &module.functions {
            let parent = function
                .parent_class_line
                .and_then(|line| module.classes.iter().find(|class| class.line == line));
            let name = parent.map_or_else(
                || function.name.clone(),
                |class| format!("{}.{}", class.name, function.name),
            );
            api.push_str(&format!(
                "- **{}** [`{}{}`]({page}#api-function-{}) — {}\n",
                labels.callable,
                name,
                function.signature,
                function.line,
                summary(function.docstring.as_deref(), labels)
            ));
        }
        api.push('\n');
    }
    if modules.is_empty() {
        api.push_str(&format!("{}\n", labels.no_modules));
    }
    write(docs_dir.join("api.md"), &api)?;

    for module in &modules {
        let connected: BTreeSet<&str> = result
            .edges
            .iter()
            .filter(|edge| edge.source == module.id || edge.target == module.id)
            .flat_map(|edge| [edge.source.as_str(), edge.target.as_str()])
            .chain(std::iter::once(module.id.as_str()))
            .filter(|id| pages.contains_key(id))
            .collect();
        let mut page = format!("{GENERATED_HEADER}# {}\n\n", module.id);
        page.push_str(&diagram(result, &connected, &pages, true, labels));
        page.push_str(&format!("\n[← {}](../index.md)\n\n", labels.back_overview));
        page.push_str(&format!("## {}\n\n", labels.description));
        page.push_str(
            &module
                .docstring
                .as_deref()
                .filter(|text| !text.trim().is_empty())
                .map(format_docstring)
                .unwrap_or_else(|| labels.missing_module_description.clone()),
        );
        page.push_str("\n\n");

        let mut documented = Vec::new();
        for class in &module.classes {
            let docstring = class
                .docstring
                .as_deref()
                .filter(|text| !text.trim().is_empty());
            documented.push((
                class.line,
                format!(
                    "<a id=\"api-class-{}\"></a>\n### class `{}`\n\n{}\n\n",
                    class.line,
                    format!("{}{}", class.name, class.signature),
                    docstring
                        .map(format_docstring)
                        .unwrap_or_else(|| labels.missing_description.clone())
                ),
            ));
        }
        for function in &module.functions {
            let docstring = function
                .docstring
                .as_deref()
                .filter(|text| !text.trim().is_empty());
            let parent = function
                .parent_class_line
                .and_then(|line| module.classes.iter().find(|class| class.line == line));
            let name = parent.map_or_else(
                || function.name.clone(),
                |class| format!("{}.{}", class.name, function.name),
            );
            documented.push((
                function.line,
                format!(
                    "<a id=\"api-function-{}\"></a>\n### {}\n\n`{}{}`\n\n{}\n\n",
                    function.line,
                    name,
                    name,
                    function.signature,
                    docstring
                        .map(format_docstring)
                        .unwrap_or_else(|| labels.missing_description.clone())
                ),
            ));
        }
        documented.sort_by_key(|(line, _)| *line);
        for (_, section) in documented {
            page.push_str(&section);
        }
        write(docs_dir.join(&pages[module.id.as_str()]), &page)?;
    }

    let manifest = pages.values().cloned().collect::<Vec<_>>().join("\n");
    let _ = write(marker_path, &manifest);
    Ok(modules.len())
}

fn write(path: PathBuf, content: &str) -> Result<(), String> {
    fs::write(&path, content).map_err(|error| format!("{}: {error}", path.display()))
}

fn write_bytes(path: PathBuf, content: &[u8]) -> Result<(), String> {
    fs::write(&path, content).map_err(|error| format!("{}: {error}", path.display()))
}

fn summary(docstring: Option<&str>, labels: &Labels) -> String {
    let cleaned = docstring.map(clean_docstring);
    let first = cleaned
        .as_deref()
        .and_then(|text| text.lines().find(|line| !line.trim().is_empty()))
        .unwrap_or(&labels.no_docstring)
        .trim();
    first.replace(['\n', '\r', '[', ']'], " ")
}

fn resolve_lang(lang: &str) -> Result<String, String> {
    let auto = lang.eq_ignore_ascii_case("auto");
    let value = if auto {
        std::env::var("LC_ALL")
            .ok()
            .filter(|s| !s.is_empty())
            .or_else(|| std::env::var("LC_MESSAGES").ok().filter(|s| !s.is_empty()))
            .or_else(|| std::env::var("LANGUAGE").ok().filter(|s| !s.is_empty()))
            .or_else(|| std::env::var("LANG").ok())
            .unwrap_or_else(|| "en".into())
    } else {
        lang.to_string()
    };
    let primary = value
        .split(['-', '_', '.'])
        .next()
        .unwrap_or("en")
        .to_ascii_lowercase();
    if translation_catalog().contains_key(&primary) {
        Ok(primary)
    } else if auto {
        Ok("en".into())
    } else {
        let supported = translation_catalog()
            .keys()
            .cloned()
            .collect::<Vec<_>>()
            .join(", ");
        Err(format!(
            "Unsupported documentation language '{lang}'. Use auto or one of: {supported}."
        ))
    }
}

#[derive(Deserialize)]
struct Labels {
    overview: String,
    modules: String,
    graph: String,
    description: String,
    back_overview: String,
    no_modules: String,
    missing_module_description: String,
    missing_description: String,
    no_docstring: String,
    open_module: String,
    no_modules_graph: String,
    api_catalog: String,
    module: String,
    class: String,
    callable: String,
}

fn labels_for_lang(lang: &str) -> &'static Labels {
    translation_catalog().get(lang).unwrap_or_else(|| {
        translation_catalog()
            .get("en")
            .expect("English translations exist")
    })
}

fn translation_catalog() -> &'static HashMap<String, Labels> {
    static CATALOG: OnceLock<HashMap<String, Labels>> = OnceLock::new();
    CATALOG.get_or_init(|| {
        serde_json::from_str(include_str!("mkdocs_i18n.json"))
            .expect("MkDocs translation catalog must be valid JSON")
    })
}

fn clean_docstring(text: &str) -> String {
    let lines: Vec<&str> = text.lines().collect();
    let indent = lines
        .iter()
        .skip(1)
        .filter(|line| !line.trim().is_empty())
        .map(|line| line.len() - line.trim_start().len())
        .min()
        .unwrap_or(0);
    let mut cleaned = Vec::new();
    if let Some(first) = lines.first() {
        cleaned.push(first.trim().to_string());
    }
    for line in lines.iter().skip(1) {
        cleaned.push(line.get(indent..).unwrap_or("").trim_end().to_string());
    }
    cleaned.join("\n").trim().to_string()
}

fn section_title(value: &str) -> Option<&'static str> {
    match value
        .trim()
        .trim_end_matches(':')
        .to_ascii_lowercase()
        .as_str()
    {
        "args" | "arguments" | "parameters" | "keyword args" | "keyword arguments" => {
            Some("Parameters")
        }
        "returns" | "return" => Some("Returns"),
        "yields" | "yield" => Some("Yields"),
        "raises" | "exceptions" => Some("Raises"),
        "attributes" => Some("Attributes"),
        "examples" => Some("Examples"),
        "notes" => Some("Notes"),
        "warning" | "warnings" => Some("Warnings"),
        _ => None,
    }
}

fn parameter_line(line: &str) -> Option<(String, String)> {
    let trimmed = line.trim();
    if let Some((declaration, kind)) = trimmed.split_once(" : ") {
        let name = declaration.trim().trim_start_matches('*');
        if !name.is_empty() && !name.contains(' ') {
            return Some((format!("- `{name}` (*{}*)", kind.trim()), String::new()));
        }
    }
    let (declaration, description) = trimmed.split_once(':')?;
    let declaration = declaration.trim();
    let (name, kind) = if let Some(open) = declaration.find('(') {
        let close = declaration.rfind(')')?;
        (
            declaration[..open].trim(),
            declaration[open + 1..close].trim(),
        )
    } else {
        (declaration, "")
    };
    if name.is_empty() || name.contains(' ') {
        return None;
    }
    let mut output = format!("- `{name}`");
    if !kind.is_empty() {
        output.push_str(&format!(" (*{kind}*)"));
    }
    if !description.trim().is_empty() {
        output.push_str(&format!(" — {}", description.trim()));
    }
    Some((output, name.to_string()))
}

fn format_docstring(text: &str) -> String {
    let source = clean_docstring(text);
    let lines: Vec<&str> = source.lines().collect();
    let mut body = Vec::new();
    let mut sphinx_params: Vec<(String, String, String)> = Vec::new();
    let mut sphinx_returns: Vec<String> = Vec::new();
    let mut sphinx_raises: Vec<(String, String)> = Vec::new();
    let mut section: Option<&str> = None;
    let mut index = 0;
    while index < lines.len() {
        let line = lines[index];
        let trimmed = line.trim();
        if let Some(rest) = trimmed.strip_prefix(":param ") {
            if let Some((field, description)) = rest.split_once(':') {
                let mut pieces = field.split_whitespace();
                let first = pieces.next().unwrap_or("");
                let second = pieces.next();
                let (kind, name) =
                    second.map_or((String::new(), first), |name| (first.to_string(), name));
                sphinx_params.push((
                    name.trim_start_matches('*').to_string(),
                    kind,
                    description.trim().to_string(),
                ));
            }
            index += 1;
            continue;
        }
        if let Some(rest) = trimmed.strip_prefix(":type ") {
            if let Some((name, kind)) = rest.split_once(':') {
                if let Some(param) = sphinx_params
                    .iter_mut()
                    .rev()
                    .find(|param| param.0 == name.trim().trim_start_matches('*'))
                {
                    param.1 = kind.trim().to_string();
                }
            }
            index += 1;
            continue;
        }
        if let Some(rest) = trimmed
            .strip_prefix(":return:")
            .or_else(|| trimmed.strip_prefix(":returns:"))
            .or_else(|| trimmed.strip_prefix(":yield:"))
            .or_else(|| trimmed.strip_prefix(":yields:"))
        {
            sphinx_returns.push(rest.trim().to_string());
            index += 1;
            continue;
        }
        if let Some(kind) = trimmed
            .strip_prefix(":rtype:")
            .or_else(|| trimmed.strip_prefix(":ytype:"))
        {
            if let Some(last) = sphinx_returns.last_mut() {
                last.insert_str(0, &format!("*{}* — ", kind.trim()));
            }
            index += 1;
            continue;
        }
        if let Some(rest) = trimmed.strip_prefix(":raises ") {
            if let Some((kind, description)) = rest.split_once(':') {
                sphinx_raises.push((kind.trim().to_string(), description.trim().to_string()));
            }
            index += 1;
            continue;
        }
        if index + 1 < lines.len()
            && lines[index + 1].trim().len() >= 3
            && lines[index + 1].trim().chars().all(|ch| ch == '-')
        {
            if let Some(title) = section_title(trimmed) {
                body.push(String::new());
                body.push(format!("### {title}"));
                section = Some(title);
                index += 2;
                continue;
            }
        }
        if let Some(title) = trimmed.strip_suffix(':').and_then(section_title) {
            body.push(String::new());
            body.push(format!("### {title}"));
            section = Some(title);
        } else if trimmed.is_empty() {
            body.push(String::new());
        } else if matches!(section, Some("Parameters" | "Attributes")) {
            if let Some((formatted, _)) = parameter_line(trimmed) {
                body.push(formatted);
            } else {
                body.push(format!("  {trimmed}"));
            }
        } else if section == Some("Raises") {
            if let Some((formatted, _)) = parameter_line(trimmed) {
                body.push(formatted);
            } else {
                body.push(trimmed.to_string());
            }
        } else {
            body.push(line.trim_end().to_string());
        }
        index += 1;
    }
    if !sphinx_params.is_empty() {
        body.extend([String::new(), "### Parameters".into()]);
        for (name, kind, description) in sphinx_params {
            let mut param = format!("- `{name}`");
            if !kind.is_empty() {
                param.push_str(&format!(" (*{kind}*)"));
            }
            if !description.is_empty() {
                param.push_str(&format!(" — {description}"));
            }
            body.push(param);
        }
    }
    if !sphinx_returns.is_empty() {
        body.extend([String::new(), "### Returns".into()]);
        body.extend(sphinx_returns);
    }
    if !sphinx_raises.is_empty() {
        body.extend([String::new(), "### Raises".into()]);
        for (kind, description) in sphinx_raises {
            body.push(format!("- `{kind}` — {description}"));
        }
    }
    body.join("\n").trim().to_string()
}

fn diagram(
    result: &AnalysisResult,
    ids: &BTreeSet<&str>,
    pages: &BTreeMap<&str, String>,
    from_module: bool,
    labels: &Labels,
) -> String {
    let nodes: BTreeMap<&str, String> = ids
        .iter()
        .enumerate()
        .map(|(index, id)| (*id, format!("n{index}")))
        .collect();
    let mut output = String::from("```mermaid\nflowchart LR\n");
    if ids.is_empty() {
        output.push_str(&format!(
            "  empty[{}]\n",
            serde_json::to_string(&labels.no_modules_graph).unwrap_or_default()
        ));
    }
    for (id, node) in &nodes {
        let label = serde_json::to_string(id).unwrap_or_default();
        output.push_str(&format!("  {node}[{label}]\n"));
    }
    let edges: BTreeSet<(&str, &str)> = result
        .edges
        .iter()
        .filter(|edge| {
            nodes.contains_key(edge.source.as_str()) && nodes.contains_key(edge.target.as_str())
        })
        .map(|edge| (edge.source.as_str(), edge.target.as_str()))
        .collect();
    for (source, target) in edges {
        output.push_str(&format!("  {} --> {}\n", nodes[source], nodes[target]));
    }
    for (id, node) in &nodes {
        let path = &pages[id];
        let href = if from_module {
            format!(
                "{}.html",
                path.trim_start_matches("modules/").trim_end_matches(".md")
            )
        } else {
            format!("{}.html", path.trim_end_matches(".md"))
        };
        output.push_str(&format!(
            "  click {node} href {} {}\n",
            serde_json::to_string(&href).unwrap_or_default(),
            serde_json::to_string(&labels.open_module).unwrap_or_default()
        ));
    }
    output.push_str("```\n");
    output
}

#[cfg(test)]
mod tests {
    use super::generate;
    use crate::analyze_directory;
    use std::fs;
    use tempfile::tempdir;

    #[test]
    fn generates_linked_diagrams_and_docstring_manual() {
        let project = tempdir().unwrap();
        fs::write(
            project.path().join("a.py"),
            "\"\"\"Module guide.\n    More details.\n    \"\"\"\nimport b\n\nclass Service:\n    \"\"\"Service guide.\"\"\"\n    def run(self):\n        \"\"\"Run guide.\"\"\"\n        pass\n",
        )
        .unwrap();
        fs::write(project.path().join("b.py"), "\"\"\"Second module.\"\"\"\n").unwrap();
        let result = analyze_directory(project.path()).unwrap();
        let output = tempdir().unwrap();
        super::generate_with_lang(&result, output.path(), "en").unwrap();

        let index = fs::read_to_string(output.path().join("docs/index.md")).unwrap();
        let page = fs::read_to_string(output.path().join("docs/modules/0000.md")).unwrap();
        assert!(index.contains("click n0 href \"modules/0000.html\""));
        assert!(index.contains("[a](modules/0000.md)"));
        assert!(page.find("```mermaid").unwrap() < page.find("## Description").unwrap());
        assert!(page.contains("Module guide."));
        assert!(page.contains("Module guide.\nMore details."));
        assert!(page.contains("Service guide."));
        assert!(page.contains("Run guide."));
        assert!(page.contains("click n1 href \"0001.html\""));
        assert!(page.contains("[← Overall graph](../index.md)"));

        fs::remove_file(project.path().join("b.py")).unwrap();
        let updated = analyze_directory(project.path()).unwrap();
        generate(&updated, output.path()).unwrap();
        assert!(!output.path().join("docs/modules/0001.md").exists());
    }

    #[test]
    fn generates_api_reference_in_manual_docs() {
        let project = tempdir().unwrap();
        fs::write(
            project.path().join("service.py"),
            "\"\"\"Main service module.\"\"\"\n\nclass Worker:\n    \"\"\"Worker class.\"\"\"\n    def process(self):\n        \"\"\"Process item.\"\"\"\n        pass\n",
        )
        .unwrap();
        let result = analyze_directory(project.path()).unwrap();

        let manual_docs = tempdir().unwrap();
        // 原稿の既存 index.md がある状態
        fs::write(manual_docs.path().join("index.md"), "# Manual Overview\n").unwrap();

        let count = super::generate_api_reference(&result, manual_docs.path(), "ja").unwrap();
        assert_eq!(count, 1);

        // 原稿の index.md が壊されていないこと
        let index = fs::read_to_string(manual_docs.path().join("index.md")).unwrap();
        assert_eq!(index, "# Manual Overview\n");

        // api.md と modules/0000.md が生成されていること
        assert!(manual_docs.path().join("api.md").exists());
        let api = fs::read_to_string(manual_docs.path().join("api.md")).unwrap();
        assert!(api.contains("service"));
        assert!(api.contains("Main service module."));
        assert!(api.contains("Worker"));

        let mod_page = fs::read_to_string(manual_docs.path().join("modules/0000.md")).unwrap();
        assert!(mod_page.contains("# service"));
        assert!(mod_page.contains("Main service module."));
        assert!(mod_page.contains("class `Worker`"));
    }
}

